### ISSUE TITLE
Cursors Size

### ISSUE THREAD

**Issue by ghost** [ducakar/openzone-cursors#2]
Request different Cursors in size 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96

**Comment by ghost** [comment]
4K hidpi monitor mouse pointer is too small, I like this theme

**Comment by ducakar** [comment]
These cursors are hand-made raster ones, cannot be scaled (unless blurry & blocky look is acceptable for you ...). If you want variants those sizes, make them yourself.
